### ISSUE TITLE
Cannot Load Such File

### ISSUE THREAD

**Issue by ultraherley** [frywer/custom_tables#2] opened 2019-08-29 13:33 UTC
Hi, I was trying to install your plugin, but every time i try to run the "Bundle exec rake" command the following appears:
C:\Bitnami\redmine-4.0.4-3\apps\redmine\htdocs>bundle exec rake redmine:plugins:migrate RAILS
_ENV=production --trace
rake aborted!
LoadError: cannot load such file -- rspec/core/rake_task
C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/plugins/custom_tables/lib/tasks/r
edmine.rake:1:in `require'
C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/plugins/custom_tables/lib/tasks/r
edmine.rake:1:in `<top (required)>'
C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/lib/tasks/redmine.rake:190:in `lo
ad'
C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/lib/tasks/redmine.rake:190:in `bl
ock in <top (required)>'
C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/lib/tasks/redmine.rake:190:in `ea
ch'
C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/lib/tasks/redmine.rake:190:in `<t
op (required)>'
C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rai
lties-5.2.3/lib/rails/engine.rb:650:in `load'
C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rai
lties-5.2.3/lib/rails/engine.rb:650:in `block in run_tasks_blocks'
C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rai
lties-5.2.3/lib/rails/engine.rb:650:in `each'
C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rai
lties-5.2.3/lib/rails/engine.rb:650:in `run_tasks_blocks'
C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rai
lties-5.2.3/lib/rails/application.rb:515:in `run_tasks_blocks'
C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rai
lties-5.2.3/lib/rails/engine.rb:459:in `load_tasks'
C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rai
lties-5.2.3/lib/rails/railtie.rb:190:in `public_send'
C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rai
lties-5.2.3/lib/rails/railtie.rb:190:in `method_missing'
C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/Rakefile:7:in `<top (required)>'
C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rak
e-12.3.3/lib/rake/rake_module.rb:29:in `load'
C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rak
e-12.3.3/lib/rake/rake_module.rb:29:in `load_rakefile'
C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rak
e-12.3.3/lib/rake/application.rb:703:in `raw_load_rakefile'
C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rak
e-12.3.3/lib/rake/application.rb:104:in `block in load_rakefile'
C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rak
e-12.3.3/lib/rake/application.rb:186:in `standard_exception_handling'
C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rak
e-12.3.3/lib/rake/application.rb:103:in `load_rakefile'
C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rak
e-12.3.3/lib/rake/application.rb:82:in `block in run'
C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rak
e-12.3.3/lib/rake/application.rb:186:in `standard_exception_handling'
C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rak
e-12.3.3/lib/rake/application.rb:80:in `run'
C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/gems/rak
e-12.3.3/exe/rake:27:in `<top (required)>'
C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/bin/rake
:23:in `load'
C:/Bitnami/redmine-4.0.4-3/apps/redmine/htdocs/vendor/bundle/ruby/2.5.0/bin/rake
:23:in `<main>'

Have you seen this before, or do you possibly know what might be causing this?

Thank you

**Comment by frywer** [comment] 2019-08-29 19:04
Hi @ultraherley,
It can be fixed by running the next command from redmine directory:
`bundle install`
That command will install 'rspec' gem which I use for testing. Will fix it in the next release.
Thank you.

**Comment by msslava** [comment] 2019-09-08 08:44
This does not work, an error is present...

**Comment by msslava** [comment] 2019-09-09 07:14
it worked for me after
`bundle install --with=development`

**Comment by ultraherley** [comment] 2019-09-09 14:21
> it worked for me after
> `bundle install --with=development`

This worked for me as well. Thank you @msslava!

**Comment by frywer** [comment] 2019-09-16 20:14
#6

**Comment by frywer** [comment] 2019-09-16 20:26
The problem is fixed, thanks

**Closed** 2019-09-18 09:10 UTC
Labels: bug

**Comment by mbecca** [comment] 2020-04-24 20:02
> 
> 
> The problem is fixed, thanks

Hi, 

There is no official version with this fix, right?

Regards,

M.
